### ISSUE TITLE
Could not resolve "./node_modules/astro/dist/content/consts.js"

### ISSUE THREAD

**Issue by chaegumi** [lilnasy/gratelets#101]
run `pnpm run preview`

```
  "scripts": {
    "dev": "astro dev",
    "start": "astro dev",
    "build": "astro check && astro build",
    "preview": "astro build && wrangler pages dev",
    "astro": "astro",
    "deploy": "astro build && wrangler pages deploy",
    "cf-typegen": "wrangler types"
  },
```

Could not resolve "./node_modules/astro/dist/content/consts.js" from "node_modules/.pnpm/astro-dynamic-import@1.1.1_astro@4.16.5/node_modules/astro-dynamic-import/integration.ts"

**Comment by lilnasy** [comment]
Could you show the error in a stackblitz project or a small git repo?

**Comment by chaegumi** [comment]
When I set the `output:"server"` in CloudFlare's pages, pnpm will have this issue, but there will be no problem with npm.
