### ISSUE TITLE
The Stylex Integration For Astro does not support Hot Reloading

### ISSUE THREAD

**Issue by RoboXGamer** [lilnasy/gratelets#40]
### The Stylex Integration For Astro does not support Hot Reloading.

which is issue as we have **restart the full dev** server each time we do any change

**Comment by RoboXGamer** [comment]
Wayaround is to use nodemon but that is very slow as the bigger the project gets more work to restart dev server each time

**Comment by lilnasy** [comment]
I didn't get around to hot module reloading, but it should at least show the updated styles on a page refresh. I'll look into it, thanks!
