### ISSUE TITLE
Stylex 0.4.1 peer dependency

### ISSUE THREAD

**Issue by enmanuelr** [lilnasy/gratelets#51]
Thank you so much for taking the time to make the `astro-stylex` plugin available. 

Facebook has recently released a 0.4.1 release of stylex, with some really great improvements. As far as I can tell, there are no breaking changes. https://stylexjs.com/blog/v0.4.1/

Would you please consider upgrading your peer dependency declaration to make `astro-stylex` compatible with the latest release? https://github.com/lilnasy/gratelets/blob/main/packages/stylex/package.json#L31

Thanks in advance.

**Comment by lilnasy** [comment]
@enmanuelr Thanks for the heads up!

The new version passes the tests - across the 4 frameworks 🥳

Do you want to open a PR?

It would be a matter of changing the `package.json`, running `pnpm i` to update the lockfile, and running `pnpm changeset` to say there was a version update. The message will appear to users here: [CHANGELOG.md](https://github.com/lilnasy/gratelets/blob/main/packages/stylex/CHANGELOG.md).

**Comment by lilnasy** [comment]
`astro-stylex@0.2.0` is now out, thanks for the help @enmanuelr!
