### ISSUE TITLE
Cannot find package 'astro-dynamic-import:internal' imported in ......

### ISSUE THREAD

**Issue by evertonadame** [lilnasy/gratelets#93]
After building my application im reciving this error Cannot find package 'astro-dynamic-import:internal imported from .....

Works in dev mode

Looks like vite is just ignoring the plugin

**Comment by lilnasy** [comment]
First time I'm seeing this. Could you share a small project created using https://astro.new/ that shows the error?

**Comment by lilnasy** [comment]
Closing this as I can't investigate without a reproduction of the error.

**Comment by RATIU5** [comment]
I'm also getting this error after building and I start the dev server, this error occurs. I will try to reproduce it.

**Comment by evertonadame** [comment]
I believe it's something in vite when optimizing dependencies in dev mode

try this

`export default defineConfig({
  integrations: [dynamicImport()],
  vite: {
    optimizeDeps: {
      exclude: ['astro-dynamic-import:internal'],
    },
  },
});`
